services:

  postgres:
    image: postgres:14
    container_name: sfu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sfu_db
      POSTGRES_PASSWORD: sfu_pswrd
      POSTGRES_USER: sfu_user
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      TZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d


volumes:
  redis_data:
  postgres_data: